#!/usr/bin/env bash
# selftest-sync-index.sh — task-v091/S21 C-3: sync-todos.sh --index 行为级自测(改造前置)
# [2026-09-27 task-v091 S21] 锁定 --index 全量重算产出的 INDEX.md 结构语义, 作为
# 「每 plan 多进程 → 单 awk 全量重算」重构的行为锚(改前/改后都必须全 PASS):
#   T01 rc=0 + Wrote 摘要行 / T02 头部+表头结构 / T03 行数(归档排除)+行态枚举
#   / T04 complete 落已完成区且不落待处理区 / T05 in_progress 待处理行形
#   / T06 pending 待处理行形 + 无 frontmatter sid=none / T07 goal 注释剥离+50 字符截断
#   +scope 头 10 条逗号 join+括号注记 status 归一计数 / T08 归档夹具整行消失
#   / T09 汇总计数 / T10 空 plans fail-open / T11 mtime 反映文件真实状态(全量重算无缓存)
#   / T12 行序=路径排序 / T13 待处理区仅 in_progress/pending 且字段形完整
# hermetic: 夹具全在 mktemp -d, 跑完 trap rm -rf; 不触真实 plans/。全 PASS exit 0; 任一 FAIL exit 1。
set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SYNC="$SCRIPT_DIR/sync-todos.sh"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
PASS=0; FAIL=0

pass() { PASS=$((PASS+1)); printf 'T%s PASS %s\n' "$1" "$1"; }
fail() { FAIL=$((FAIL+1)); printf 'T%s FAIL %s\n' "$1" "$2"; }

call() {  # call <plans_dir> → 跑 --index, 置 RC/COUT/CERR
  RC=0; COUT="$(bash "$SYNC" --index "$1" 2>"$TMP/err")"; RC=$?
  CERR="$(cat "$TMP/err")"
}

row_of() {  # row_of <task-id> → 取该任务表格行, 日期列归一为 DATE(消除跑测日期噪声)
  grep -F "| $1 |" "$IDX" | head -1 | sed -E 's/\| [0-9]{4}-[0-9]{2}-[0-9]{2} \|/| DATE |/'
}
sec() {  # sec <起标题> <止标题> → 截取 INDEX 区段(含起止行); 前缀匹配(真实标题带后缀括注,
         # 口径同消费方 check-conflicts.sh:97 的 /^## 待处理/,/^## 已完成/p, 禁加 $ 锚)
  sed -n "/^## $1/,/^## $2/p" "$IDX"
}

# ─── 夹具: active/complete/pending 三态 + 归档, 共 5 计划(≥4) ──────────────────
ROOT="$TMP/fixture"
P="$ROOT/plans"
IDX="$P/INDEX.md"
mkdir -p "$P/task-20260920-111101" "$P/task-20260921-111102" "$P/task-20260922-111103" \
         "$P/task-20260923-111104" "$P/archive/task-20260924-111105"

# F1 complete: 2/2 全完成, frontmatter sid/wt, scope 表 4 个点分单元格(允许+禁止列均收)
cat > "$P/task-20260920-111101/task_plan.md" <<'EOF'
---
session_id: sess-complete
worktree_path: /wt/complete
---
# Task complete

## Goal
Complete task goal line

## ⚠️ 执行范围限制

| 类别 | 允许 | 禁止 |
|------|------|------|
| 脚本 | a1.sh | b1.sh |
| 文档 | a2.md | b2.md |

### Phase 1: one
- [x] step
- **Status:** complete（2026-09-19）

### Phase 2: two
- [x] step
- **Status:** complete
EOF

# F2 active: 1/3(in_progress 带括号注记), 无 scope 区段 → scope_files 空单元格
cat > "$P/task-20260921-111102/task_plan.md" <<'EOF'
---
session_id: sess-active
worktree_path: /wt/active
---
# Task active

## Goal
Active task goal line

### Phase 1: one
- [x] step
- **Status:** complete

### Phase 2: two
- [ ] step
- **Status:** in_progress(2026-09-27, S21 注记)

### Phase 3: three
- [ ] step
- **Status:** pending
EOF

# F3 pending: 0/2 全未开始, 无 frontmatter(sid→none, wt→空)
cat > "$P/task-20260922-111103/task_plan.md" <<'EOF'
# Task pending

## Goal
Pending task goal

### Phase 1: one
- [ ] step
- **Status:** pending

### Phase 2: two
- [ ] step
- **Status:** pending
EOF

# F4 meta-rich: goal 首行 HTML 注释(剥离)+缩进长行(50 截断), scope 12 条(验证头 10 上限),
# status 含小写与括号注记
G58="VisibleGoalLine-Pad0123456789012345678901234567890123456789"
{
  printf -- '---\nsession_id: sess-rich\nworktree_path: /wt/rich\n---\n'
  printf -- '# Task rich\n\n## Goal\n\n<!-- hidden hint -->\n   %s\n\n' "$G58"
  printf -- '## 执行范围限制\n\n| 类别 | 允许 | 禁止 |\n|------|------|------|\n'
  for i in 01 02 03 04 05 06 07 08 09 10 11 12; do
    printf -- '| 组 | r%s.sh | x%s.sh |\n' "$i" "$i"
  done
  printf -- '\n### Phase 1: one\n- [x] step\n- **Status:** complete\n\n'
  printf -- '### Phase 2: two\n- [ ] step\n- **status:** in_progress（2026-09-27, note）\n'
} > "$P/task-20260923-111104/task_plan.md"

# F5 归档: 完成态但位于 plans/archive/ 深度 3 → 不得出现在 INDEX 任何位置
cat > "$P/archive/task-20260924-111105/task_plan.md" <<'EOF'
# Task archived

## Goal
Archived task goal

### Phase 1: one
- [x] step
- **Status:** complete
EOF

# T01 基本面: rc=0, stdout 摘要, INDEX.md 落盘, stderr 无噪声
call "$P"
if [ "$RC" = 0 ] && printf '%s' "$COUT" | grep -q '^\[index\] Wrote .*/INDEX.md (in_progress=2 pending=1 complete=1)$' \
   && [ -f "$IDX" ] && [ -z "$CERR" ]; then pass 01; else fail 01 "rc=$RC out=$COUT err=$CERR"; fi

# T02 头部+表头结构(逐字节)
if [ "$(sed -n '1p' "$IDX")" = "# Task Index" ] \
   && [ "$(sed -n '2p' "$IDX")" = "<!-- Auto-generated by sync-todos.sh --index. 勿手改，重跑脚本刷新。 -->" ] \
   && sed -n '3p' "$IDX" | grep -q '^<!-- Last refreshed: [0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}_[0-9]\{2\}:[0-9]\{2\} -->$' \
   && grep -qF '> 恢复时先读本文件：in_progress=中断待续 / pending=未开始 / complete=已完成。' "$IDX" \
   && grep -qFx '| Task ID | Status | Phase 进度 | Goal | session_id | worktree | scope_files | 最后更新 | 待办 |' "$IDX" \
   && grep -qFx '|---------|--------|-----------|------|---------|------|' "$IDX"; then
  pass 02
else
  fail 02 "head=$(sed -n '1,12p' "$IDX" | tr '\n' '/')"
fi

# T03 行数=4(归档排除)+每行态枚举合法
ROWS="$(grep -c '^| task-' "$IDX")"
BADROWS="$(grep '^| task-' "$IDX" | grep -Evc '^\| task-[0-9-]+ \| (complete|in_progress|pending) \| [0-9]+/[0-9]+ \| ')"
if [ "$ROWS" = 4 ] && [ "$BADROWS" = 0 ]; then pass 03; else fail 03 "rows=$ROWS bad=$BADROWS"; fi

# T04 complete: 表行字段齐(含 scope 允许+禁止列全收)+落已完成区+不落待处理区
R4="$(row_of task-20260920-111101)"
DONE_SEC="$(sec 已完成 汇总)"
TODO_SEC="$(sec 待处理 已完成)"
if [ "$R4" = "| task-20260920-111101 | complete | 2/2 | Complete task goal line | sess-complete | /wt/complete | a1.sh,b1.sh,a2.md,b2.md | DATE | ✓ |" ] \
   && printf '%s' "$DONE_SEC" | grep -qE '^- task-20260920-111101 ✓ \(2/2\) — [0-9]{4}-[0-9]{2}-[0-9]{2}$' \
   && ! printf '%s' "$TODO_SEC" | grep -q 'task-20260920-111101'; then
  pass 04
else
  fail 04 "row=$R4 done=$(printf '%s' "$DONE_SEC" | tr '\n' '/')"
fi

# T05 in_progress 待处理行形(括号注记 status 计入 in_progress; 无 scope 区段→空单元格;
# 行形断言用 grep -e 防 '- ' 开头被解析为选项)
if [ "$(row_of task-20260921-111102)" = "| task-20260921-111102 | in_progress | 1/3 | Active task goal line | sess-active | /wt/active |  | DATE | ⚠ 续 |" ] \
   && printf '%s' "$TODO_SEC" | grep -qxF -e '- **task-20260921-111102** — in_progress, Phase 1/3（中断恢复首选）'; then
  pass 05
else
  fail 05 "row=$(row_of task-20260921-111102)"
fi

# T06 pending 待处理行形+无 frontmatter → sid=none, wt/scope 空格占位
if [ "$(row_of task-20260922-111103)" = "| task-20260922-111103 | pending | 0/2 | Pending task goal | none |  |  | DATE | ⚠ 未开始 |" ] \
   && printf '%s' "$TODO_SEC" | grep -qxF -e '- **task-20260922-111103** — pending, 未开始 (0/2)'; then
  pass 06
else
  fail 06 "row=$(row_of task-20260922-111103)"
fi

# T07 goal 注释剥离+前导空白剥离+50 截断; scope 12 条→头 10 条逗号 join; 小写 status 计数
GEXP="${G58:0:50}"
SEXP="$(printf 'r%s.sh,x%s.sh,' 01 01 02 02 03 03 04 04 05 05 | sed 's/,$//')"
if [ "$(row_of task-20260923-111104)" = "| task-20260923-111104 | in_progress | 1/2 | ${GEXP} | sess-rich | /wt/rich | ${SEXP} | DATE | ⚠ 续 |" ]; then
  pass 07
else
  fail 07 "row=$(row_of task-20260923-111104) sexp=$SEXP"
fi

# T08 归档夹具: 深度 3 计划在 INDEX 全文零出现(全量重算天然删行, 防 29.6 统计回归)
if ! grep -q 'task-20260924-111105' "$IDX"; then pass 08; else fail 08 "$(grep -n 'task-20260924-111105' "$IDX")"; fi

# T09 汇总行计数
if grep -qFx -- '- in_progress: 2 | pending: 1 | complete: 1' "$IDX"; then pass 09; else fail 09 "$(grep '^## 汇总' -A2 "$IDX" | tail -1)"; fi

# T10 空 plans fail-open: 写 _No tasks found_ 而非报错
EMPTY="$TMP/empty/plans"; mkdir -p "$EMPTY"
call "$EMPTY"
if [ "$RC" = 0 ] && grep -qF "_No tasks found under $EMPTY" "$EMPTY/INDEX.md"; then pass 10; else fail 10 "rc=$RC out=$COUT"; fi

# T11 mtime 反映文件真实状态(v3 全量重算口径: 无 mtime 缓存/跳过, touch 即生效)
touch -d '2020-01-01 12:00' "$P/task-20260922-111103/task_plan.md"
call "$P"
if grep -F 'task-20260922-111103' "$IDX" | grep -qF '| 2020-01-01 |'; then pass 11; else fail 11 "$(grep -F 'task-20260922-111103' "$IDX" | head -1)"; fi

# T12 行序=find 路径字典序(与旧实现 sort 口径一致)
ORDER="$(grep '^| task-' "$IDX" | awk -F'|' '{gsub(/ /,"",$2); print $2}' | tr '\n' ' ')"
if [ "$ORDER" = "task-20260920-111101 task-20260921-111102 task-20260922-111103 task-20260923-111104 " ]; then
  pass 12
else
  fail 12 "order=$ORDER"
fi

# T13 待处理区仅 in_progress/pending 且字段形完整(消费方 check-conflicts.sh:97 依赖 ^- \*\*)
BADTODO="$(printf '%s' "$TODO_SEC" | grep '^- \*\*' | grep -Evc '^- \*\*task-[0-9-]+\*\* — (in_progress, Phase [0-9]+/[0-9]+（中断恢复首选）|pending, 未开始 \([0-9]+/[0-9]+\))$')"
NTODO="$(printf '%s' "$TODO_SEC" | grep -c '^- \*\*')"
if [ "$NTODO" = 3 ] && [ "$BADTODO" = 0 ]; then pass 13; else fail 13 "n=$NTODO bad=$BADTODO"; fi

printf 'Total: %d PASS=%d FAIL=%d\n' "$((PASS+FAIL))" "$PASS" "$FAIL"
exit $((FAIL > 0))
